version: "3.9"

services:
  app:
    container_name: app
    build: .
    volumes:
      - type: bind
        source: ./process.py
        target: /project/process.py
        read_only: true
      - type: bind
        source: ./figures
        target: /project/figures
        read_only: false
    restart: unless-stopped
    entrypoint: [ "tail", "-f", "/dev/null" ]